### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by vbjay** [ad-si/shaven#44]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'shaven@0.8.1',
npm WARN EBADENGINE   required: { node: '~0.12.2' },
npm WARN EBADENGINE   current: { node: 'v15.3.0', npm: '7.0.14' }
npm WARN EBADENGINE }

**Comment by ad-si** [comment]
Did you install the latest version? It should have fixed this issue.

**Comment by ad-si** [comment]
1.1.0 is the latest version, so I guess you haven't 😛

**Comment by vbjay** [comment]
I tried npm update and was not aware that depth has to be given now.

**Comment by vbjay** [comment]
package.json and lock files
[AdminUI.Admin npm update.zip](https://github.com/ad-si/shaven/files/5647268/AdminUI.Admin.npm.update.zip) after update
[AdminUI.Admin original.zip](https://github.com/ad-si/shaven/files/5647269/AdminUI.Admin.original.zip)  Exactly as the project came.  


http://npm.broofa.com/ may help

**Comment by vbjay** [comment]
See  imsky/holder#232.  This is the problem.

**Comment by vbjay** [comment]
Closing because it isn't your project that is the problem.  It's the fact that holder is _holding_ 😁 onto a really old version of your package.
